name=input("Enter your name:")
birthmonth=input("Enter your birth month:")
birthday=input("Enter your birth date:")
birthyear=input("Enter your birth year")
print(name, ", your birthday is on",birthmonth,birthday,",",birthyear,"!")