import turtle
turtle.forward(100)
turtle.left(87)
turtle.setheading(127)
turtle.goto(50,50)
turtle.home()
turtle.circle(25)
asdf=turtle.isdown()
qwerty=turtle.xcor()
werty=turtle.ycor()
print(asdf)
print(qwerty)
print(werty)